### ISSUE TITLE
"common" stanzas are lost (meaning, inlined)

### ISSUE THREAD

**Issue by peti** [pikajude/stylish-cabal#10]
The Cabal construct:

~~~
common default-flags
  default-language:     Haskell2010
  ghc-options:          -Wall -Wcompat -threaded

executable ackermann
  import:               default-flags
  main-is:              ackermann.hs
  build-depends:        base <5, modular-arithmetic
~~~

comes out as

~~~
executable ackermann
  main-is:          ackermann.hs
  build-depends:    base < 5, modular-arithmetic
  default-language: Haskell2010
  ghc-options:      -Wall -Wcompat -threaded

  if impl(ghc > 8.4)
    buildable: False
~~~

after `stylish-cabal -is` has run. This is not ideal.

**Comment by peti** [comment]
Ping? Is there any chance this issue can be fixed? This currently is a deal-breaker for me since I use common stanzas quite a lot in my code and love them. It would be so cool if `stylish-cabal` could retain those.

**Comment by pikajude** [comment]
@peti totally missed this in my github notifications noise. I'll try to get to it today, but I'm not sure whether Cabal exposes if fields came from a `common` stanza or not.

**Comment by pikajude** [comment]
@peti Cabal does not. This is a root issue with stylish-cabal that I'm going to address in the next major release. Basically, it's a pretty printer, not a formatter - I'm using an un-annotated AST as the data structure, and all the transformations Cabal's parser does have already been performed on it. Common stanzas have been floated in, unrecognized fields have been dropped, etc.

**Comment by peti** [comment]
What a shame. I suppose it makes sense from Cabal's point of view, though. Thank you very much for taking the time to investigate this feature.
