### ISSUE TITLE
Please support haddock-library 1.7.x and Cabal 2.4.x

### ISSUE THREAD

**Issue by peti** [pikajude/stylish-cabal#11]
Nixpkgs has updated to hspec 2.5.x as per LTS-12.x. Unfortunately, this means that we can no longer build stylish-cabal.

**Comment by peti** [comment]
5 months later ... and `hspec` is at 2.6.1 these days. I wonder whether you reading this bug tracker at all? Maybe you didn't enable notifications from github or something?

Anyhow, there are a number of new versions of dependencies that `stylish-cabal` sadly won't accept and therefore doesn't build in Nixpkgs without a plethora of overrides that I'm feeling less and less inclined to maintain. :-(

**Comment by peti** [comment]
For what it's worth: http://packdeps.haskellers.com/feed?needle=stylish-cabal

**Comment by pikajude** [comment]
Thanks for the followup ping! I don't check github notifications because it shows me all activity for all repos I watch and every thread I've commented in, so it's totally useless to me. A better way to get in contact is to ping me on Freenode (same username). I'll fix this as soon as I can.

**Comment by pikajude** [comment]
I uploaded 0.4.1.0 which supports hspec >= 2.5 (since they added skipping test cases).

**Comment by peti** [comment]
https://github.com/NixOS/nixpkgs/commit/dd98e07fed9abe82f43dec5497b7978d413266ff manages to build `stylish-cabal` with ghc 8.4.4, at least. Unfortunately, the build with the current default compiler, ghc 8.6.3, is still broken.

**Comment by peti** [comment]
stylish-cabal-0.5.0.0 supports these versions.
