### ISSUE TITLE
Test suite failure in stylish-cabal-0.1.0.0

### ISSUE THREAD

**Issue by peti** [pikajude/stylish-cabal#2]
Citing from https://hydra.nixos.org/build/69690150:

~~~
Test suite roundtrip: RUNNING...

comprehensive check
  retains every attribute FAILED [1]

Failures:

  tests/roundtrip/Main.hs:12: 
  1) comprehensive check retains every attribute
       uncaught exception: IOException of type NoSuchThing (tests/example.cabal: openFile: does not exist (No such file or directory))

Randomized with seed 298316960

Finished in 0.0004 seconds
1 example, 1 failure
Test suite roundtrip: FAIL
~~~

**Comment by pikajude** [comment]
Thanks! What a silly mistake. Will fix the tarball with ~0.1.1.0~ 0.2 (might as well push out the doc/test improvements as well)

**Comment by peti** [comment]
This tool looks very useful, indeed. I'm looking forward to having a working build in Nix. :smile:

**Comment by pikajude** [comment]
Just pushed https://hackage.haskell.org/package/stylish-cabal-0.2.0.0. Fingers crossed that my build-from-sdist test script did its job properly.

**Comment by pikajude** [comment]
I manually changed the hash and version of stylish-cabal in `hackage-packages.nix` and was able to successfully build on my machine. Closing.

**Comment by peti** [comment]
> Fingers crossed that my build-from-sdist test script did its job properly.

You could just generate a test script with https://github.com/haskell-CI/haskell-ci. See https://github.com/pikajude/stylish-cabal/pull/3.
