### ISSUE TITLE
stylish-cabal-0.3.0.0 fails during Haddock stage

### ISSUE THREAD

**Issue by peti** [pikajude/stylish-cabal#6]
Citing from https://hydra.nixos.org/build/70754838:

~~~
Running Haddock on library 'test-utils' for stylish-cabal-0.3.0.0..
Setup: internal error when calculating transitive package dependencies.
Debug info: []
~~~

Not sure what this means.

**Comment by pikajude** [comment]
As the error message suggests, this is a Cabal bug: https://github.com/haskell/cabal/issues/4969

Since it's been fixed in `cabal new-build`, I'd recommend `dontHaddock` for stylish-cabal until the nixpkgs Haskell module builder uses the new-* cabal operations.

**Comment by peti** [comment]
Well, the Nixpkgs module builder is *never* going to use `cabal new-build`. It's using `runhaskell Setup.hs build` etc., and I don't see that code switching to new-style builds in Cabal in the foreseeable future.

**Comment by pikajude** [comment]
Then this bug fix is contingent on whether old-build can ever generate Haddocks for an internal library :(
